### PR TITLE
DAG-1144: Add start and limit options to versions_by_project call

### PR DESCRIPTION
**Pull request by zamj**

### CODE REVIEW

**Review by dbradf — COMMENTED** [review]
Could you create an evergreen.py specific jira ticket for this? This is a public repo, but you are referencing a private jira ticket.

**Comment by zamj** [comment]
> Could you create an evergreen.py specific jira ticket for this? This is a public repo, but you are referencing a private jira ticket.

Sorry about that, fixed now

**Comment by dbradf** [comment]
This should still be a DAG ticket, not an EVG ticket. But the component should be 'evergreen.py' and the privacy should be public.

**Review by dbradf — APPROVED** [review]

**Comment by zamj** [comment]
evergreen merge

**Pull request merged**
