### PR TITLE
Add support to get and set user permissions

### PR DESCRIPTION
**Pull request by viveksunder**
* Implements these APIs -
** https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#give-permissions-to-user
** https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#get-user-permissions
* Adds a CLI command to get user permissions

### CODE REVIEW

**Comment by viveksunder** [comment]
Note - The documentation for https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#give-permissions-to-user mentions `superuser` as being a supported resource type. But I can't find an example for what the associated permissions look like. I've assumed this implementation will work for this resource type as well.

**Review by dbradf — APPROVED** [review]

**Comment by dbradf** [comment]
evergreen merge

**Comment by viveksunder** [comment]
Removed a print statement that I had in a test while trying to debug it.

Also, not sure why the tests are failing. Appears to be related to build tooling and not the code itself.

**Comment by dbradf** [comment]
evergreen merge

**Comment by dbradf** [comment]
I'm not sure what caused the test failure. It looks like there was an issue downloading the dependencies. The tests are passing now. And the change has been merged and published.

**Pull request merged**
